ack.lang({
	'Reader Cloud' : 'Reader Cloud',
	'make a book your own' : 'make a book your own',
	'Connectivity Problem' : 'Connectivity Problem',
	'You don\'t appear to be connected to the internet' : 'You don\'t appear to be connected to the internet',
	'Please reconnect to the internet and try again' : 'Please reconnect to the internet and try again',
	'Error' : 'Error',
	'There was a problem communicating with the server.' : 'There was a problem communicating with the server.',
	'Do you want to try reloading the widget?' : 'Do you want to try reloading the widget?',
	'There was a problem communicating with the server.' : 'There was a problem communicating with the server.',
	'Do you want to try reloading the widget?' : 'Do you want to try reloading the widget?',
	'A link to these attachments will be added:' : 'A link to these attachments will be added:',
	'Compose a new Tweet' : 'Compose a new Tweet',
	'Back' : 'Back',
	'Tweet' : 'Tweet',
	'Share or Export with Reader Cloud' : 'Share or Export with Reader Cloud',
	'Just one more step...' : 'Just one more step...',
	'We need to know your e-mail address & link your twitter account.' : 'We need to know your e-mail address & link your twitter account.',
	'Linked with Twitter' : 'Linked with Twitter',
	'Linked with Facebook' : 'Linked with Facebook',
	'Avatar' : 'Avatar',
	'Update' : 'Update',
	'Save' : 'Save',
	'your book data' : 'your book data',
	'Load' : 'Load',
	'Sign in to save or load your book data.' : 'Sign in to save or load your book data.',
	'You only need to do this once' : 'You only need to do this once',
	'Sign in with Reader Cloud' : 'Sign in with Reader Cloud',
	'Not registered?' : 'Not registered?',
	'Create a free account in seconds' : 'Create a free account in seconds',
	'Sign out' : 'Sign out',
	'Close' : 'Close',
	'Sign up to Reader Cloud' : 'Sign up to Reader Cloud',
	'It\'s free and all you need is an e-mail address' : 'It\'s free and all you need is an e-mail address',
	'Sign in to Reader Cloud' : 'Sign in to Reader Cloud',
	'Signout' : 'Signout',
	'Load from Reader Cloud' : 'Load from Reader Cloud',
	'Save to Reader Cloud' : 'Save to Reader Cloud',
	'Change account email address' : 'Change account email address',
	'Update your email' : 'Update your email',
	'Enter your new email address below' : 'Enter your new email address below',
	'Your new email address is the same as your current one' : 'Your new email address is the same as your current one',
	'All done' : 'All done',
	'Your email address has been changed' : 'Your email address has been changed',
	'You need to be connected to the internet to use this widget' : 'You need to be connected to the internet to use this widget',
	'Continue anyway' : 'Continue anyway',
	'This action' : 'This action',
	'saves' : 'saves',
	'your data from this book to the cloud.' : 'your data from this book to the cloud.',
	'You can access it later and continue where you left off' : 'You can access it later and continue where you left off',
	'Cancel' : 'Cancel',
	'Next' : 'Next',
	'loads' : 'loads',
	'any saved data for this book from the cloud.' : 'any saved data for this book from the cloud.',
	'Any updates you\'ve made to this book since you last saved to the cloud will be overwritten, you may want to save it to the cloud first.' : 'Any updates you\'ve made to this book since you last saved to the cloud will be overwritten, you may want to save it to the cloud first.',
	'Saving to Reader Cloud' : 'Saving to Reader Cloud',
	'Saving your book to Reader Cloud. If it\'s taking a while why not grab a coffee?' : 'Saving your book to Reader Cloud. If it\'s taking a while why not grab a coffee?',
	'Finish' : 'Finish',
	'Load from Reader Cloud' : 'Load from Reader Cloud',
	'Loading your book from Reader Cloud. If it\'s taking a while why not grab a coffee?' : 'Loading your book from Reader Cloud. If it\'s taking a while why not grab a coffee?',
	'Okay' : 'Okay',
	'Yes' : 'Yes',
	'No' : 'No',
	'Adult Help Needed...' : 'Adult Help Needed...',
	'This is what you\'re trying to do:' : 'This is what you\'re trying to do:',
	'To allow this please answer the question below' : 'To allow this please answer the question below',
	'What is' : 'What is',
	'add' : 'add',
	'Back' : 'Back',
	'Verify' : 'Verify',
	'Whoops!' : 'Whoops!',
	'The answer you gave wasn\'t correct. Please try again' : 'The answer you gave wasn\'t correct. Please try again',
	'Working' : 'Working',
	'Database Error' : 'Database Error',
	'There was a problem with database. You may experience unwanted side effects. The error was' : 'There was a problem with database. You may experience unwanted side effects. The error was',
	'Your E-mail address' : 'Your E-mail address',
	'you@email.com' : 'you@email.com',
	'Your Password' : 'Your Password',
	'Forgotten your password?' : 'Forgotten your password?',
	'By signing in with Reader Cloud you agree to the terms and conditions found' : 'By signing in with Reader Cloud you agree to the terms and conditions found',
	'here' : 'here',
	'Authenticate with Reader Cloud' : 'Authenticate with Reader Cloud',
	'Reset Complete' : 'Reset Complete',
	'Instructions on how to reset your password have been e-mailed to you' : 'Instructions on how to reset your password have been e-mailed to you',
	'Incorrect Password' : 'Incorrect Password',
	'The password you entered was not correct' : 'The password you entered was not correct',
	'Logout from Reader Cloud' : 'Logout from Reader Cloud',
	'Are you sure you want to Sign out?' : 'Are you sure you want to Sign out?',
	'If you Sign out and don\'t sync your book with Reader Cloud you will lose all your Reader Cloud data' : 'If you Sign out and don\'t sync your book with Reader Cloud you will lose all your Reader Cloud data',
	'Sign out' : 'Sign out',
	'Upload to Reader Cloud & Sign out' : 'Upload to Reader Cloud & Sign out',
	'A link to these attachments will be added:' : 'A link to these attachments will be added:',
	'What\'s on your mind?' : 'What\'s on your mind?',
	'Back' : 'Back',
	'Post' : 'Post',
	'Share or Export with Reader Cloud' : 'Share or Export with Reader Cloud',
	'We need to know your e-mail address & link your facebook account.' : 'We need to know your e-mail address & link your facebook account.',
	'Attachments' : 'Attachments',
	'To' : 'To',
	'to@email.com' : 'to@email.com',
	'Subject' : 'Subject',
	'Share or Export with Reader Cloud' : 'Share or Export with Reader Cloud',
	'Please Complete' : 'Please Complete',
	'You need to enter the address of someone to send the email to' : 'You need to enter the address of someone to send the email to',
	'You need to enter a subject' : 'You need to enter a subject',
	'We need to know who to send the email from.' : 'We need to know who to send the email from.',
	'Reader Cloud terms and conditions' : 'Reader Cloud terms and conditions',
	'These are also available online at' : 'These are also available online at',
	'Email' : 'Email',
	'Twitter' : 'Twitter',
	'Facebook' : 'Facebook',
	"Updates available" : "Updates available",
	"Updates for this widget have been found. Would you like to apply them now?" : "Updates for this widget have been found. Would you like to apply them now?",
	"Your link will be automatically added" : "Your link will be automatically added",
	"Evernote" : "Evernote",
	'These attachments will be saved' : 'These attachments will be saved',
	'Notebook name' : 'Notebook name',
	'Leave this blank to save to your default notebook' : 'Leave this blank to save to your default notebook',
	'We need to know your e-mail address so that we can save this to Evernote.' : 'We need to know your e-mail address so that we can save this to Evernote.',
	'My Notebook' : 'My Notebook',
	'Evernote email notes to address' : 'Evernote email notes to address',
	'user.1234@m.evernote.com' : 'user.1234@m.evernote.com',
	'This is not your normal e-mail address. You can find this under your evernote settings' : 'This is not your normal e-mail address. You can find this under your evernote settings',
	'You need to enter your evernote notes to address' : 'You need to enter your evernote notes to address',
	'Your evernote notes to address normally ends with "@m.evernote.com"' : 'Your evernote notes to address normally ends with "@m.evernote.com"',
	'To find this address follow the steps below…' : 'To find this address follow the steps below…',
	'Open the evernote app or website' : 'Open the evernote app or website',
	'Visit your account setting' : 'Visit your account setting',
	'Then find your "Evernote email address"' : 'Then find your "Evernote email address"',
	'Room pin' : 'Room pin',
	'Rooms let you share information with a few select people that you choose.' : 'Rooms let you share information with a few select people that you choose.',
	'Learn more' : 'Learn more',
	'Join' : 'Join',
	'Join a Room' : 'Join a Room',
	'Join a Room with Reader Cloud' : 'Join a Room with Reader Cloud',
	'Whoops' : 'Whoops',
	'It doesn\'t look like that room exists. Check the pin again and try again.' : 'It doesn\'t look like that room exists. Check the pin again and try again.',
	'Create a room so that you can share information privately with other readers' : 'Create a room so that you can share information privately with other readers',
	'More about Rooms' : 'More about Rooms',
	'Create' : 'Create',
	'Create a Room' : 'Create a Room',
	'Create a Room with Reader Cloud' : 'Create a Room with Reader Cloud',
	'Here\'s the pin for your room. Give this to other readers so that they can join your room' : 'Here\'s the pin for your room. Give this to other readers so that they can join your room',
	'Join me in my Reader Cloud room. The pin is' : 'Join me in my Reader Cloud room. The pin is',
	'Share your room pin' : 'Share your room pin',
	'How do you want to share your room pin?' : 'How do you want to share your room pin?',
	'All done!' : 'All done!',
	'The email has been sent' : 'The email has been sent',
	'The tweet has been sent' : 'The tweet has been sent',
	'Your status has been updated' : 'Your status has been updated',
	'This has been saved to your notebook' : 'This has been saved to your notebook',
	'Reader Cloud Rooms' : 'Reader Cloud Rooms',
	'Room' : 'Room',
	'Leave Room' : 'Leave Room',
	'Current Room' : 'Current Room',
	'Screen Name' : 'Screen Name',
	'Bob' : 'Bob',
	'This is how other readers will see you' : 'This is how other readers will see you',
	'We need to know your email address to create a room' : 'We need to know your email address to create a room',
	'Reader Cloud Rooms let you connect and interact with other readers of the same book – locally or remotely and in realtime  For example, from within an iBook an educator can create a Room for a particular lesson and invite students to join that Room (physically or virtually). Once participating in the same Room, educators and students can:' : 'Reader Cloud Rooms let you connect and interact with other readers of the same book – locally or remotely and in realtime  For example, from within an iBook an educator can create a Room for a particular lesson and invite students to join that Room (physically or virtually). Once participating in the same Room, educators and students can:',
	'Educators' : 'Educators',
	'See who is in the Room.' : 'See who is in the Room.',
	'See widget data entered by each student e.g. quiz answers.' : 'See widget data entered by each student e.g. quiz answers.',
	'Drive widget page mirroring for students to follow in real-time.' : 'Drive widget page mirroring for students to follow in real-time.',
	'Students' : 'Students',
	'Follow the educator’s progression in real-time.' : 'Follow the educator’s progression in real-time.',
	'Enter data into the widgets and submit to the educator.' : 'Enter data into the widgets and submit to the educator.',
	'Save data for later.' : 'Save data for later.',
	'To create a room you will need to enter a screen name and e-mail address. You’ll be provided with a pin number to share with your other collaborators. To join a room it’s even simpler. Just enter an optional screen name and the room and you’re there.' : 'To create a room you will need to enter a screen name and e-mail address. You’ll be provided with a pin number to share with your other collaborators. To join a room it’s even simpler. Just enter an optional screen name and the room and you’re there.',
	'Guest' : 'Guest',
	'Change your screen name' : 'Change your screen name',
	'Update your Screen Name' : 'Update your Screen Name',
	'Enter your new screen name below' : 'Enter your new screen name below',
	'All done' : 'All done',
	'Your screen name has been changed' : 'Your screen name has been changed',
	'The maximum number of users in this room has been reached' : 'The maximum number of users in this room has been reached',
	'To add more you can visit your Reader Cloud' : 'To add more you can visit your Reader Cloud',
	'account page' : 'account page',
	'Share' : 'Share',
	'How do you want to share this?' : 'How do you want to share this?',
	'This book has many great interactive features that need adult supervision such as saving and emailing pictures' : 'This book has many great interactive features that need adult supervision such as saving and emailing pictures',
	'zero' : 'zero',
	'one' : 'one',
	'two' : 'two',
	'three' : 'three',
	'four' : 'four',
	'five' : 'five',
	'six' : 'six',
	'seven' : 'seven',
	'eight' : 'eight',
	'nine' : 'nine',
	'To continue please enter the code' : 'To continue please enter the code',
	'For grown ups' : 'For grown ups',
	'wipes' : 'wipes',
	'all Reader Cloud data stored on this device.' : 'all Reader Cloud data stored on this device.',
	'Warning' : 'Warning',
	'Any updates you\'ve made to this book will be lost. This cannot be undone.' : 'Any updates you\'ve made to this book will be lost. This cannot be undone.',
	'Wipe this book' : 'Wipe this book',
	'Wiping the data on this device' : 'Wiping the data on this device',
	'Are you sure?' : 'Are you sure?'
});
ack.lang({
	'Undo' : 'Undo',
	'Redo' : 'Redo',
	'Erase' : 'Erase',
	'Color' : 'Color',
	'Width' : 'Width',
	'Share' : 'Share',
	'Are you sure you want to delete your drawing and start again?' :'Are you sure you want to delete your drawing and start again?',
	"Do you want to email this drawing to yourself?<br/>You will need to create a free account with Bookry - it's free and takes seconds. Would you like to do this now?" : "Do you want to email this drawing to yourself?<br/>You will need to create a free account with Bookry - it's free and takes seconds. Would you like to do this now?",
	"Great! Your drawing has been e-mailed to you." : "Great! Your drawing has been e-mailed to you.",
	"Email Drawing" : "Email Drawing",
	"Do you want to e-mail a copy of your drawing to yourself?" : "Do you want to e-mail a copy of your drawing to yourself?",
	'By doing this you are agreeing to share your drawing and e-mail address with the author.' : 'By doing this you are agreeing to share your drawing and e-mail address with the author.',
	'By doing this you are agreeing to share your e-maill address with the author.' : 'By doing this you are agreeing to share your e-maill address with the author.',
	'By doing this you are agreeing to share your drawing with the author.' : 'By doing this you are agreeing to share your drawing with the author.',
	'Email Drawing' : 'Email Drawing',
	'Message' : 'Message',
	'All done!' : 'All done!',
	'Are you sure?' : 'Are you sure?',
	'How do you want to share your drawing' : 'How do you want to share your drawing',
	'Share what you\'ve drawn' : 'Share what you\'ve drawn',
	'The tweet has been sent' : 'The tweet has been sent',
	'Your status has been updated' : 'Your status has been updated',
	'This has been saved to your notebook' : 'This has been saved to your notebook'
});