
ack.module("ack.widget",function(s){var g=null,e={win:null,lose:null,match:null,nomatch:null,select:null};s.init=function(){ack.tools.background({supportsPadding:!1,element:$("#board")});e.select=(new ack.tools.Audio(__settings__.select_audio)).loadOnNextInteraction();e.nomatch=(new ack.tools.Audio(__settings__.nomatch_audio)).loadOnNextInteraction();e.match=(new ack.tools.Audio(__settings__.match_audio)).loadOnNextInteraction();e.lose=(new ack.tools.Audio(__settings__.lose_audio)).loadOnNextInteraction();
e.win=(new ack.tools.Audio(__settings__.win_audio)).loadOnNextInteraction();var b=$('<img src="restart.png" title="'+ack.lang("Restart")+'" alt="'+ack.lang("Restart")+'" />');ack.ui.common.bindTap(b,function(){ack.ui.dialog.confirm(ack.lang("Restart"),ack.lang("Do you want to restart?"),function(){ack.widgetdb.clear(function(){n();$("#lose, #win").fadeOut(function(){$("#lose, #win").remove()})})})});ack.ui.toolbar.addToolbarItem(b);$("#board").width(__settings__.search_area_width).height(__settings__.search_area_height);
__settings__.score.show?(ack.tools.styles.addRules([["#hud .score",ack.tools.styles.generateStyle("background-color",__settings__.score["background-color"])],["#hud .score",__settings__.score.font]]),ack.widgetdb.get("score",function(a){a=a||0;ack.widgetdb.set("score",a,function(){o(a)})})):$("#hud .score").remove();__settings__.time.show?ack.tools.styles.addRules([["#hud .time",ack.tools.styles.generateStyle("background-color",__settings__.time["background-color"])],["#hud .time",__settings__.time.font]]):
$("#hud .time").remove();ack.ui.common.bindTap($("#board"),function(){m()&&ack.ui.dialog.confirm(ack.lang("Restart"),ack.lang("Do you want to restart?"),function(){ack.widgetdb.clear(function(){n();$("#lose, #win").fadeOut(function(){$("#lose, #win").remove()})})})});n()};var u=function(){$("#board .item.source").draggable({start:function(){var b=$(this),a=parseInt(b.attr("data-index")),c=parseInt(b.attr("data-subindex")),d=$('#board .item.target[data-index="'+a+'"]');__settings__.size_to_target_on_drag&&
b.css({width:__settings__.items[a].target.w,height:__settings__.items[a].target.h,"margin-left":(__settings__.items[a].sources[c].w-__settings__.items[a].target.w)/2,"margin-top":(__settings__.items[a].sources[c].h-__settings__.items[a].target.h)/2});e.match.pause();e.nomatch.pause();e.select.play(0);"true"===d.attr("data-matched")&&d.attr("data-matched-index")==a&&d.attr("data-matched-subindex")==c&&(d.fadeTo(200,1),d.removeAttr("data-matched data-hidden data-matched-index data-matched-subindex"),
b.removeAttr("data-dropped"),__settings__.size_to_target_on_drag?b.css({width:__settings__.items[a].target.w,height:__settings__.items[a].target.h,"margin-left":(__settings__.items[a].sources[c].w-__settings__.items[a].target.w)/2,"margin-top":(__settings__.items[a].sources[c].h-__settings__.items[a].target.h)/2}):b.css({width:__settings__.items[a].sources[c].w,height:__settings__.items[a].sources[c].h,"margin-left":0,"margin-right":0}),ack.widgetdb.remove("source-item-"+a+"-"+c),ack.widgetdb.get("score",
function(b){b=b||0;b-=parseInt(__settings__.items[a].score);ack.widgetdb.set("score",b,function(){o(b)})}))},stop:function(b,a){var c=$(this);if("1"!==c.attr("data-dropped")){var d=parseInt(c.attr("data-index")),h=parseInt(c.attr("data-subindex"));__settings__.size_to_target_on_drag&&c.css({width:__settings__.items[d].sources[h].w,height:__settings__.items[d].sources[h].h,"margin-left":0,"margin-top":0});e.match.pause();e.select.pause();e.nomatch.play(0);t(this,"#board .item.target").not('[data-hidden="true"]').length?
c.animate(a.originalPosition,200):__settings__.revert?c.animate({top:__settings__.items[d].sources[h].y,left:__settings__.items[d].sources[h].x},200):ack.widgetdb.set("source-item-"+d+"-"+h,{x:a.position.left,y:a.position.top,r:p(this)})}}});$("#board .item.source").click(function(){if(__settings__.enable_rotation){var b=this,a=p(this)+1,b=$(b),a=a%4;b.removeClass("rotation0 rotation1 rotation2 rotation3").addClass("rotation"+a);$(this).addClass("anim")}});$("#board .item.target").droppable({accept:function(b){return b.hasClass("item")&&
b.hasClass("source")&&b.attr("data-index")===$(this).attr("data-index")&&p(b)===p(this)?!0:!1},drop:function(b,a){var c=$(a.draggable.context).add(this),d=c.filter(".source"),h=c.filter(".target"),l=parseInt(h.attr("data-index")),k=parseInt(d.attr("data-subindex")),c=__settings__.items[l].target,q=__settings__.items[l].sources[k];h.removeClass("activated");e.nomatch.pause();e.select.pause();e.match.play(0);ack.widgetdb.get("score",function(a){a=a||0;a+=parseInt(__settings__.items[l].score);ack.widgetdb.set("score",
a,function(){o(a)})});if("true"===h.attr("data-matched")){var f=parseInt(h.attr("data-matched-index")),j=parseInt(h.attr("data-matched-subindex")),i;if(f!==l||j!==k)ack.widgetdb.remove("source-item-"+f+"-"+j),i=$('#board .item.source[data-index="'+f+'"][data-subindex="'+j+'"]'),f=__settings__.items[f].sources[j],i.css({width:f.w,height:f.h}).animate({top:f.y,left:f.x},200),i.draggable("enable")}d.attr("data-dropped","1");ack.widgetdb.set("source-item-"+l+"-"+k,!0);__settings__.size_to_target_on_drop?
d.css({width:c.w+"px",height:c.h+"px","margin-left":0,"margin-top":0}):d.css({width:q.w+"px",height:q.h+"px","margin-left":0,"margin-top":0});d.animate({top:(__settings__.size_to_target_on_drop?c.y:c.y+(c.h-q.h)/2)+"px",left:(__settings__.size_to_target_on_drop?c.x:c.x+(c.w-q.w)/2)+"px"},200,function(){h.fadeTo(200,0);h.attr({"data-matched":"true","data-matched-index":l,"data-matched-subindex":k,"data-hidden":"true"});__settings__.drag_after_match||d.draggable("disable");__settings__.remove_on_match&&
d.fadeOut();m()&&r()})},activate:function(){"easy"===__settings__.difficulty&&$(this).addClass("activated")},deactivate:function(){"easy"===__settings__.difficulty&&$(this).removeClass("activated")},over:function(){"medium"===__settings__.difficulty&&$(this).addClass("activated")},out:function(){"medium"===__settings__.difficulty&&$(this).removeClass("activated")}})},v=function(b){for(var a=[],c=0;c<__settings__.items.length;c++)for(var d=0;d<__settings__.items[c].sources.length;d++)a.push("source-item-"+
c+"-"+d);ack.widgetdb.getMulti(a,function(a){for(var c=0;c<__settings__.items.length;c++){var d=__settings__.items[c].target,e,f,j=$("<div></div>").attr({"data-index":c,"class":"item target rotation"+d.r+" norotanim"}).css({"background-image":"url("+d.image+")",top:d.y+"px",left:d.x+"px",width:d.w+"px",height:d.h+"px"});$("#board").append(j);for(var i=0;i<__settings__.items[c].sources.length;i++){e=__settings__.items[c].sources[i];f=a["source-item-"+c+"-"+i];var g=$("<div></div>").attr({"data-index":c,
"data-subindex":i,"class":"item source rotation"+(void 0===f?e.r:f.r)+" norotanim"}).css({"background-image":"url("+e.image+")",top:(void 0===f?e.y:f.y)+"px",left:(void 0===f?e.x:f.x)+"px",width:e.w+"px",height:e.h+"px"});$("#board").append(g);u();f&&(j.css("opacity","0"),j.attr({"data-matched":"true","data-matched-index":c,"data-matched-subindex":i,"data-hidden":"true"}),__settings__.size_to_target_on_drop?g.css({top:d.y+"px",left:d.x+"px",width:d.w+"px",height:d.h+"px"}):g.css({top:d.y+(d.h-e.h)/
2+"px",left:d.x+(d.w-e.w)/2+"px",width:e.w+"px",height:e.h+"px"}),__settings__.remove_on_match&&g.hide(),__settings__.drag_after_match||g.draggable("disable"))}}b()})},o=function(b){__settings__.score.show&&(void 0!==b?$("#hud>.score").text(b):ack.widgetdb.get("score",function(){$("#hud>.score").text(b||0)}))},x=function(){!0===__settings__.time.show&&ack.widgetdb.get("timer_start",function(b){g=setInterval(function(){var a=(new Date).getTime(),c=new Date(1E3*__settings__.time.allowed_secs-(a-b));
0>c.getTime()?($("#hud .time").text("00 : 00"),clearInterval(g),!1===m()&&w()):m()?$("#hud .time").text("00 : 00"):(a=c.getMinutes(),a=10>a?"0"+a:a,c=c.getSeconds(),c=10>c?"0"+c:c,$("#hud .time").text(a+" : "+c))},500)})},y=function(b){!0!==__settings__.time.show?b():ack.widgetdb.get("timer_start",function(a){void 0===a||null===a?ack.widgetdb.set("timer_start",(new Date).getTime(),function(){b()}):b()})},t=function(b,a){var c=$(),d=$(b),e=d.offset(),g=[e.left,e.left+d.outerWidth()],k=[e.top,e.top+
d.outerHeight()];$(a).each(function(){var a=$(this),b=a.offset(),d=[b.left,b.left+a.outerWidth()],b=[b.top,b.top+a.outerHeight()];g[0]<d[1]&&g[1]>d[0]&&k[0]<b[1]&&k[1]>b[0]&&(c=c.add(a))});return c},p=function(b){b=$(b);return b.hasClass("rotation0")?0:b.hasClass("rotation1")?1:b.hasClass("rotation2")?2:b.hasClass("rotation3")?3:0},n=function(){try{$("#board .item.source").draggable("destroy")}catch(b){}$("#board .item.target").droppable("destroy");$("#board .item").remove();v(function(){o(0);clearInterval(g);
y(function(){x();m()&&r()})});for(var a in e)e[a]&&e[a].pause()},m=function(){return 0===$('#board .item.target:not([data-matched="true"])').length?!0:!1},r=function(b){!0!==b&&ack.book.history.markCompleted();__settings__.win_image||(__settings__.win_image="win.png");if(__settings__.win_image){var a=$('<div id="win" style="display:none;"></div>');ack.ui.common.bindTap(a,function(){a.fadeOut(function(){a.remove()});e.win.pause()});$("#ack-widget").append(a);ack.tools.background({supportsPadding:!1,
element:a,backgroundKey:"win_image",backgroundCssKey:"win_image_css"});a.fadeIn();clearInterval(g);e.win.play(0)}},w=function(){__settings__.lose_image||(__settings__.lose_image="lose.png");if(__settings__.lose_image){var b=$('<div id="lose" style="display:none;"></div>');ack.ui.common.bindTap(b,function(){ack.widgetdb.clear(function(){n()});b.fadeOut(function(){b.remove()});e.lose.pause()});$("#ack-widget").append(b);ack.tools.background({supportsPadding:!1,element:b,backgroundKey:"lose_image",backgroundCssKey:"lose_image_css"});
b.fadeIn();clearInterval(g);e.lose.play(0)}}});
