
ack.module("ack.widget",function(q){var f=null,c=null,i=null,e={win:null,time:null};q.init=function(){e.match=(new ack.tools.Audio(__settings__.match.audio)).loadOnNextInteraction();e.time=(new ack.tools.Audio(__settings__.time.audio)).loadOnNextInteraction();e.win=(new ack.tools.Audio(__settings__.win.audio)).loadOnNextInteraction();ack.tools.background({paddingCallback:function(a,g,d){g=document.querySelector("#ack-widget-inner");a=a.replace("padding-","");g.style[a]=d}});m();n(function(){o(!0)});
__settings__.time.has_timer?new ack.tools.timer.CountDown(1E3*__settings__.time.allowed,function(a){c=a;c.onTick=function(){i.text(c.remainingFormatted);c.isEnded&&r(function(){j(function(){k()})})};c.isPaused?c.resume():j(function(){c.start()})}):j(function(){});$(window).resize(p);var a=$('<img src="restart.png" alt="'+ack.lang("Restart")+'" title="'+ack.lang("Restart")+'" />');ack.ui.common.bindTap(a,function(){ack.ui.dialog.confirm(ack.lang("Restart"),ack.lang("Do you want to restart?"),function(){c&&
c.stop();k()})});ack.ui.toolbar.addToolbarItem(a[0]);__settings__.time.has_timer&&(i=$("<span></span>"),ack.ui.toolbar.addToolbarItem(i[0]))};var m=function(){for(var a=[],b=0;b<__settings__.grid_width;b++)a.push("<td></td>");a=a.join("");for(b=0;b<__settings__.grid_height;b++)$("#grid").append("<tr>"+a+"</tr>");p()},p=function(){var a=$("#grid"),b=a.parent(),g=b.width(),b=b.height(),d=Math.min(g/__settings__.grid_width,b/__settings__.grid_height),c=d*__settings__.grid_width,d=d*__settings__.grid_height;
a.width(c).height(d).css({"margin-top":(b-d)/2+"px","margin-left":(g-c)/2+"px"})},n=function(a){$("#ack-widget-inner").append($('<img src="'+__settings__.card_cover+'">').load(function(){$(this).remove();s(function(b){ack.widgetdb.get("found",function(g){for(var g=g||{},d=0;d<b.length;d++)for(var c=0;c<b[d].length;c++){var e=b[d][c];g[e]||$($($("#grid tr").get(d)).find("td").get(c)).append(['<div class="card-container" data-card="'+e+'">','<div class="card" style="background-image:url(\''+__settings__.cards[e]+
"')\">","</div>",'<div class="card-cover" style="background-image:url(\''+__settings__.card_cover+"')\">","</div></div>"].join(""))}ack.ui.common.bindTap($("#grid td"),function(a){t($(this).find(".card-container"));a.preventDefault()});a&&a()})})}))},t=function(a){if(!(a.is(".found")||f&&a.get(0)===f.get(0)))if(f){var b=f;f=null;a.addClass("active");b.attr("data-card")!==a.attr("data-card")?(a.data("inactiveTimeout",setTimeout(function(){a.removeClass("active")},600+__settings__.visible_duration)),
b.data("inactiveTimeout",setTimeout(function(){b.removeClass("active")},600+__settings__.visible_duration))):(e.match.play(0),a.addClass("found"),b.addClass("found"),ack.widgetdb.get("found",function(a){a=a||{};a[b.attr("data-card")]=!0;ack.widgetdb.set("found",a)}),setTimeout(function(){a.parent().addClass("out");b.parent().addClass("out");setTimeout(function(){a.parent().removeClass("out");b.parent().removeClass("out");a.remove();b.remove();o()},600)},600))}else $("#grid .card-container.active").removeClass("active"),
f=a,a.data("inactiveTimeout")&&(clearTimeout(a.data("inactiveTimeout")),a.data("inactiveTimeout",null)),a.addClass("active")},s=function(a){ack.widgetdb.get("ordering",function(b){if(b)a(b);else{for(var b=[],c=[],d=0;d<__settings__.grid_width*__settings__.grid_height/2;d++)c.push(d),c.push(d);for(d=0;d<__settings__.grid_height;d++){var e=[];b.push(e);for(var f=0;f<__settings__.grid_width;f++){var h=c.splice(Math.floor(Math.random()*c.length),1)[0];e.push(h)}}ack.widgetdb.set("ordering",b,function(){a(b)})}})},
k=function(a){$("#grid").empty();$("#ack-widget .modal").remove();for(var b in e)e[b].pause();m();f=null;ack.widgetdb.removeMulti(["ordering","found"],function(){n(function(){c&&c.start();a&&a()})})},o=function(a){0===$("#grid .card-container").length&&(c&&c.stop(),u(function(){k()}),!0!==a&&ack.book.history.markCompleted())},l=function(a,b,c,d,e,f){var h=$(['<div class="modal">',c?'<div class="banner">'+c+"</div>":"","</div>"].join(""));ack.tools.background({element:h,backgroundKey:a,backgroundCssKey:b});
c&&(ack.tools.styles.setFont(h.find(".banner"),d),h.find(".banner").css("backgrounc-color",e||"transparent"));$("#ack-widget").append(h);ack.ui.common.bindTap(h,function(){h.remove();f&&f()})},u=function(a){__settings__.win.show?(e.win.play(0),l("win.image","win.image_css",__settings__.win.text,__settings__.win.font,__settings__.win.background,function(){e.win.pause();a()})):setTimeout(a,0)},j=function(a){__settings__.start.show?l("start.image","start.image_css",__settings__.start.text,__settings__.start.font,
__settings__.start.background,function(){a()}):setTimeout(a,0)},r=function(a){__settings__.time.has_timer?(e.time.play(0),l("time.image","time.image_css",__settings__.time.text,__settings__.time.font,__settings__.time.background,function(){e.time.pause();a()})):setTimeout(a,0)}});
