
ack.module("ack.widget",function(j){var i=null,k=null,e=[],f=[],l=function(a,b){ack.comms.useLessCPU();i=e.length;f=[];e.push({width:ack.widget.toolbar.width(),color:ack.widget.toolbar.color(),points:[{x:a,y:b}],type:ack.widget.toolbar.tool()})},c=function(a,b){if(null!==i){var m=e[i],h=m.points[m.points.length-1].x;6<m.length&&5>Math.abs(a-h)&&5>Math.abs(a-h)||(m.points.push({x:a,y:b}),ack.widget.draw.ppLine(m.width,m.color,m.points,m.type))}},b=function(a,b){ack.comms.useNormalCPU();c(a,b);i=null;
ack.widget.draw.all(e);ack.widgetdb.setMulti({elements:e,undone:f})};j.undo=function(){if(e.length){i=null;var a=e.splice(e.length-1,1);f.push(a[0]);ack.widget.draw.all(e);ack.widgetdb.setMulti({elements:e,undone:f})}};j.redo=function(){if(f.length){i=null;var a=f.splice(f.length-1,1);e.push(a[0]);ack.widget.draw.all(e);ack.widgetdb.setMulti({elements:e,undone:f})}};j.clear=function(){ack.ui.dialog.confirm(ack.lang("Are you sure?"),ack.lang("Are you sure you want to delete your drawing and start again?"),
function(){i=null;e=[];ack.widget.draw.all(e);ack.widgetdb.setMulti({elements:e,undone:f})})};var n=function(a,b){var m=$(a).offset();return{x:b.clientX+document.body.scrollLeft+document.documentElement.scrollLeft-Math.floor(m.left),y:b.clientY+document.body.scrollTop+document.documentElement.scrollTop-Math.floor(m.top)+1}};j.init=function(){ack.comms.auth.onLoggedOut(function(){window.location.reload()});if(__settings__.color_palette)for(var a=$("#colors .col"),g=0;g<__settings__.color_palette.length;g++)a[g]&&
$(a[g]).attr("data-color",__settings__.color_palette[g]).css("background-color",__settings__.color_palette[g]);ack.widget.toolbar.render();a=function(){var a=$("#canvas-container").width(),b=$("#canvas-container").height(),c=$("#canvas")[0];c.width=""+a;c.height=""+b;ack.widget.draw.all(e)};$(window).resize(a);ack.ui.overlay.addCallback(a);a();$("#canvas-foreground").mousedown(function(a){a=n($("#canvas"),a);l(a.x,a.y);return!1});$("#canvas-foreground").mousemove(function(a){a=n($("#canvas"),a);c(a.x,
a.y);return!1});$("#canvas-foreground").mouseup(function(a){a=n($("#canvas"),a);b(a.x,a.y);return!1});$("#canvas-foreground").bind("touchstart",function(a){a=a.originalEvent;if(!k){var b=a.changedTouches[0];k=b.identifier;l(b.pageX,b.pageY-ack.ui.toolbarHeightPx());a.preventDefault()}});$("#canvas-foreground").bind("touchmove",function(a){for(var a=a.originalEvent,b=0;b<a.changedTouches.length;b++)if(a.changedTouches[b].identifier===k){b=a.changedTouches[b];c(b.pageX,b.pageY-ack.ui.toolbarHeightPx());
a.preventDefault();break}});$("#canvas-foreground").bind("touchend touchcancel",function(a){for(var a=a.originalEvent,c=0;c<a.changedTouches.length;c++)if(a.changedTouches[c].identifier===k){var g=a.changedTouches[c];k=null;b(g.pageX,g.pageY-ack.ui.toolbarHeightPx());a.preventDefault()}});ack.widget.draw.all(e);$("#canvas-container").css("background-color",__settings__.background_col?__settings__.background_col:"#FFFFFF");ack.widgetdb.getMulti(["elements","undone"],function(a){a.elements&&a.undone&&
(e=a.elements,f=a.undone,ack.widget.draw.all(e))})}});
ack.module("ack.widget.toolbar",function(j){var i=[],k="#000000",e=[2,10,30,60],f=1,l="line",c=null;j.render=function(){k=$("#colors .col").first().attr("data-color");for(var b=0;b<i.length;b++)ack.ui.toolbar.removeToolbarItem(i[b]);i=[];b=$('<img src="undo.png" alt="'+ack.lang("Undo")+'" title="'+ack.lang("Undo")+'" />');ack.ui.common.bindTap(b,function(a){ack.widget.undo();a.preventDefault()});i.push(b[0]);b=$('<img src="redo.png" alt="'+ack.lang("Redo")+'" title="'+ack.lang("Redo")+'" />');ack.ui.common.bindTap(b,
function(a){ack.widget.redo();a.preventDefault()});i.push(b[0]);b=$('<img src="clear.png" alt="'+ack.lang("Clear")+'" title="'+ack.lang("Clear")+'" />');ack.ui.common.bindTap(b,function(a){ack.widget.clear();a.preventDefault()});i.push(b[0]);var f=$('<img src="erase.png" alt="'+ack.lang("Erase")+'" title="'+ack.lang("Erase")+'" />').css({"-webkit-border-radius":"3px","-moz-border-radius":"3px","border-radius":"3px"});ack.ui.common.bindTap(f,function(a){l="line"===l?"erase":"line";f.css("background-color",
"erase"===l?"#00a0ff":"transparent");a.preventDefault()});i.push(f[0]);c=f;if(__settings__.can_export_evernote||__settings__.can_export_facebook||__settings__.can_export_twitter||__settings__.can_export)b=$('<img src="'+ack.ui.rc.share.easy.icon()+'" alt="'+ack.lang("Share")+'" title="'+ack.lang("Share")+'" />'),ack.ui.common.bindTap(b,function(a){a.preventDefault();ack.ui.rc.hide();var b=ack.widget.draw.asDataURL(),a={};__settings__.can_export&&(a[ack.ui.rc.share.Formats.EMAIL]={prefilledTo:(ack.comms.auth.details()||
{}).email,prefilledSubject:ack.lang("Look at what I've drawn!"),assets:[b]});__settings__.can_export_twitter&&(a[ack.ui.rc.share.Formats.TWITTER]={prefilledMessage:ack.lang("Look at what I've drawn!"),assets:[b]});__settings__.can_export_facebook&&(a[ack.ui.rc.share.Formats.FACEBOOK]={prefilledMessage:ack.lang("Look at what I've drawn!"),assets:[b]});__settings__.can_export_evernote&&(a[ack.ui.rc.share.Formats.EVERNOTE]={assets:[b]});ack.ui.rc.share.selection(ack.lang("Share what you've drawn"),ack.lang("How do you want to share your drawing?"),
a,function(a,c){var f="",e="",n="";switch(a){case ack.ui.rc.share.Formats.EMAIL:f="image_export";e=ack.lang("All done!");n=ack.lang("The email has been sent");break;case ack.ui.rc.share.Formats.TWITTER:f="image_export_twitter";e=ack.lang("All done!");n=ack.lang("The tweet has been sent");break;case ack.ui.rc.share.Formats.FACEBOOK:f="image_export_facebook";e=ack.lang("All done!");n=ack.lang("Your status has been updated");break;case ack.ui.rc.share.Formats.EVERNOTE:f="image_export_evernote",e=ack.lang("All done!"),
n=ack.lang("This has been saved to your notebook")}var i=ack.ui.loading.show();c.image=[b];c.background=__settings__.background_col?__settings__.background_col:"#FFFFFF";ack.comms.request(f,c,function(){ack.ui.loading.hide(i);ack.ui.dialog.alert(e,n);ack.ui.rc.hide()},function(a,b){ack.ui.loading.hide(i);ack.ui.rc.common.serverCommsFail({response:a,status:b})},{successAlert:{title:e,message:n}})})}),i.push(b[0]);i.push($("<div></div>")[0]);for(b=i.length-1;0<=b;b--)ack.ui.toolbar.addToolbarItem(i[b])};
j.width=function(){return e[f]};j.color=function(){return k};j.tool=function(){return l};$(document).ready(function(){ack.ui.common.bindTap($("#colors .col"),function(b){b.preventDefault();k=$(this).attr("data-color");$("#colors").find(".col").removeClass("active");$(this).addClass("active");l="line";c&&c.css("background-color","transparent")});ack.ui.common.bindTap($("#colors .width"),function(b){b.preventDefault();f=parseInt($(this).attr("data-index"));$("#colors").find(".width").each(function(b,
a){a=$(a);a.attr("data-index")==f?a.attr("src","width"+f+"a.png"):a.attr("src","width"+a.attr("data-index")+".png")})})})});
ack.module("ack.widget.draw",function(j){var i=null,k=null;j.all=function(c){k=c;var b=f().getContext("2d");b.clearRect(0,0,f().width,f().height);b.beginPath();b.fillStyle=__settings__.background_col?__settings__.background_col:"#FFFFFF";b.fillRect(0,0,f().width,f().height);b.fill();i&&b.drawImage(i[0],0,0,f().width,f().height);for(var e=0;e<c.length;e++)switch(c[e].type){case "line":var a=b,g=c[e].width,j=c[e].color,h=c[e].points;if(0!==h.length)if(a.strokeStyle=j,a.lineJoin="round",a.lineWidth=
g,2===h.length&&h[0].x===h[1].x&&h[0].y===h[1].y)a.beginPath(),a.fillStyle=j,a.arc(h[0].x,h[0].y,g/2,0,2*Math.PI,!1),a.fill();else{if(6>h.length){a.moveTo(h[0].x,h[0].y);a.beginPath();for(g=0;g<h.length;g++)a.lineTo(h[g].x,h[g].y)}else{a.beginPath();a.moveTo(h[0].x,h[0].y);for(g=1;g<h.length-2;g++)j=(h[g].x+h[g+1].x)/2,d=(h[g].y+h[g+1].y)/2,a.quadraticCurveTo(h[g].x,h[g].y,j,d);a.quadraticCurveTo(h[g].x,h[g].y,h[g+1].x,h[g+1].y)}a.stroke()}break;case "erase":l(b,c[e].width,c[e].color,c[e].points)}};
j.ppLine=function(c,b,e,a){switch(a){case "line":a=f().getContext("2d");a.strokeStyle=b;a.lineJoin="round";a.lineWidth=c;a.moveTo(e[0].x,e[0].y);a.beginPath();for(c=0;c<e.length;c++)a.lineTo(e[c].x,e[c].y);a.stroke();break;case "erase":l(f().getContext("2d"),c,b,e)}};j.asDataURL=function(){j.all(k||[]);var c=document.createElement("canvas");c.width=f().width;c.height=f().height;var b=c.getContext("2d");b.fillStyle=__settings__.background_col?__settings__.background_col:"#FFFFFF";b.fillRect(0,0,f().width,
f().height);b.drawImage(f(),0,0);__settings__.foreground_image&&$("#canvas-foreground img").length&&b.drawImage($("#canvas-foreground img")[0],0,0,f().width,f().height);c=c.toDataURL();j.all(k||[]);return c};if(__settings__.background_image){var e=$('<img src="'+__settings__.background_image+'" />').hide();$(document.body).append(e);e.load(function(){i=e;j.all(k||[])})}__settings__.foreground_image&&$("#canvas-foreground").append($('<img src="'+__settings__.foreground_image+'" />'));var f=function(){return $("#canvas")[0]},
l=function(c,b,e,a){e=c.globalCompositeOperation;c.globalCompositeOperation="destination-out";c.strokeStyle="rgba(0,0,0,1.0)";c.lineJoin="round";c.lineWidth=b;c.moveTo(a[0].x,a[0].y);c.beginPath();for(b=0;b<a.length;b++)c.lineTo(a[b].x,a[b].y);c.stroke();c.globalCompositeOperation=e}});
